### ISSUE TITLE
TypeError: node.render is not a function

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#4] opened 2015-05-14 14:33 UTC
@jails I just experimented a little. If you use the *h()** helper in the test cases as a stand-alone function, and try to run - as one example this test case **can patch embedded text node** outside jasmine - as a stand alone function. It will throw, and you will see this message in the console.log **TypeError: node.render is not a function**

This is just a random test case I picked as en example for this issue, but it have impact on other test cases as well.

Very strange indeed, because the tests runs just fine.

**Comment by jails** [comment] 2015-05-14 14:37
Is it possible to reproduce what you did on a https://jsfiddle.net/ ? Not sure to get how this can be generated

**Comment by jails** [comment] 2015-05-14 14:43
You should be able to use this url as https://rawgit.com/crysalead-js/dom-layer/master/dist/dom-layer.min.js a vendor file

**Comment by justmeandtaken** [comment] 2015-05-14 14:49
@jails I'm working on it. There are more strange things here I can't get to work just now. Example render children and mount the node without using the h() function, just only this at the end [...] when I create a child(*ren*).

As soon as I have tested everything I will let you know.

**Comment by jails** [comment] 2015-05-14 14:56
This is a simple example of a div which contain a span which contain "Hello world" for example, hope that helps https://jsfiddle.net/8y8ph6uu/

**Comment by justmeandtaken** [comment] 2015-05-14 14:58
@jails It helps, but not so very much when I get messages that Tree don't contain a mount function even if the new keyword are used. Strange indeed.

It also seems that each mounting never got a unique number, all mounting I do give me mountId 1.

**Comment by justmeandtaken** [comment] 2015-05-14 15:02
@jails Give it 1 day and I will test your whole code and give you a issue list as soon as I'm done.

**Comment by jails** [comment] 2015-05-14 15:03
`new Tree()` must be done only once (id are related to a tree instance so if you deal with many tree instances, you can have as many `id=1` as you have tree instances). Looks like it's working on this fiddle https://jsfiddle.net/84b4cy9c/

**Comment by jails** [comment] 2015-05-15 13:56
I'm closing this since I wasn't able to reproduce this error.

**Closed by jails** 2015-05-15 13:56 UTC
